apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: backend
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deployment
  namespace: backend
  labels:
    app: backend1
spec:
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: nginx #BACKEND_APP:TAG
        ports:
        - containerPort: 8123
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: app-secret
        - configMapRef:
            name: app-configs
---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: backend1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: v1
data:
  MONGO_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  MONGO_USER: bW9uZ28=
  RABBITMQ_USER: cmFiYml0Cg==
  RABBITMQ_PASS: c3VwZXJzZWNyZXRwYXNzd29yZA==
kind: Secret
metadata:
  name: app-secret
  namespace: backend
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
  namespace: backend
data:
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "15672"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: frontend
roleRef:
  kind: ClusterRole
  name: app-reader
  apiGroup: rbac.authorization.k8s.io
