apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: db
  name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: db
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: mongo-storage
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: mongo-secret
        volumeMounts:
        - name: vol
          mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: db
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  MONGO_INITDB_ROOT_USERNAME: bW9uZ28=
kind: Secret
metadata:
  name: mongo-secret
  namespace: db
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  # storageClassName: default
